import { useEffect, useState, type FormEvent, type MouseEvent, type ReactNode } from 'react'
import type { StorefrontApiResponse } from '../api/storefront'

type Props = { storefront: StorefrontApiResponse; onNavigate: (path: string) => (event: MouseEvent<HTMLAnchorElement>) => void }
type Section = 'overview' | 'products' | 'orders' | 'payments' | 'returns' | 'customers' | 'messages' | 'analytics' | 'settings'
type Product = { id: string; name: string; category: string; priceMinor: number; stock: number; isActive: boolean }
type Row = { id: string; orderNumber: string; status: string; totalMinor: number }
const sections: { id: Section; label: string }[] = [{ id: 'overview', label: 'Overview' }, { id: 'products', label: 'Products' }, { id: 'orders', label: 'Orders' }, { id: 'payments', label: 'Payments' }, { id: 'returns', label: 'Returns' }, { id: 'customers', label: 'Customers' }, { id: 'messages', label: 'Messages' }, { id: 'analytics', label: 'Analytics' }, { id: 'settings', label: 'Settings' }]

export function AdminPage({ onNavigate }: Props) {
  const [section, setSection] = useState<Section>('overview'); const [notice, setNotice] = useState(''); const [data, setData] = useState<any>({})
  const load = (url: string, key: string) => fetch(url).then(r => r.ok ? r.json() : null).then(body => body && setData((current: any) => ({ ...current, [key]: body }))).catch(() => undefined)
  useEffect(() => { if (section === 'overview' || section === 'analytics') load('/api/admin/analytics', 'analytics'); if (section === 'products') load('/api/admin/products', 'products'); if (section === 'orders') load('/api/admin/orders', 'orders'); if (section === 'payments') load('/api/admin/payments', 'payments'); if (section === 'returns') load('/api/admin/returns', 'returns'); if (section === 'customers') load('/api/admin/customers', 'customers'); if (section === 'settings') load('/api/admin/settings', 'settings') }, [section])
  const submit = async (event: FormEvent<HTMLFormElement>, url: string, method: string, success: string) => { event.preventDefault(); const values = Object.fromEntries([...new FormData(event.currentTarget).entries()].map(([key, value]) => [key, String(value)])); if (values.price) values.priceMinor = String(Number(values.price) * 100); const response = await fetch(url, { method, headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(values) }); setNotice(response.ok ? success : 'Request could not be completed.'); if (response.ok && url === '/api/admin/products') load(url, 'products') }
  const patchProduct = async (product: Product, changes: Partial<Product>) => { const response = await fetch(`/api/admin/products/${product.id}`, { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(changes) }); setNotice(response.ok ? 'Product updated.' : 'Product update failed.'); if (response.ok) setData((d: any) => ({ ...d, products: { products: d.products.products.map((p: Product) => p.id === product.id ? { ...p, ...changes } : p) } })) }
  const patchStatus = async (url: string, body: object, message: string) => { const response = await fetch(url, { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) }); setNotice(response.ok ? message : 'Update failed.') }
  const analytics = data.analytics ?? {}; const products: Product[] = data.products?.products ?? []; const orders: Row[] = data.orders?.orders ?? []; const payments = data.payments?.payments ?? []; const returns = data.returns?.returns ?? []; const customers = data.customers?.customers ?? []
  return <section className="admin-page page-section"><div className="admin-heading"><div><p className="eyebrow">ADMINISTRATION</p><h1>Gadgify control center</h1><p className="hero-text">Manage your store from one workspace.</p></div><a className="secondary-button" href="/" onClick={onNavigate('/')}>View storefront</a></div><div className="admin-shell"><aside className="admin-sidebar">{sections.map(item => <button key={item.id} className={section === item.id ? 'is-active' : ''} type="button" onClick={() => { setSection(item.id); setNotice('') }}>{item.label}</button>)}</aside><div className="admin-content">
    {section === 'overview' && <><div className="admin-stat-grid"><Stat label="Revenue" value={`₹${((analytics.revenueMinor ?? 0) / 100).toLocaleString('en-IN')}`} /><Stat label="Orders" value={analytics.orders ?? 0} /><Stat label="Customers" value={analytics.customers ?? 0} /><Stat label="Products" value={analytics.products ?? 0} /></div><Panel text="Create products, monitor orders, process refunds, message customers, and configure store settings from the sections on the left." /></>}
    {section === 'products' && <><Title title="Products & inventory" text="Create products, manage pricing, stock, and visibility." /><form className="admin-form" onSubmit={e => submit(e, '/api/admin/products', 'POST', 'Product saved successfully.')}><label>Product name<input name="name" required /></label><label>Category<input name="category" required /></label><label>Price (₹)<input name="price" type="number" min="0" step="0.01" required /></label><label>Stock<input name="stock" type="number" min="0" required /></label><label className="full">Description<textarea name="description" rows={4} /></label><button className="primary-button" type="submit">Save product</button></form>{products.length ? <Table><table className="admin-table"><thead><tr><th>Product</th><th>Price</th><th>Stock</th><th>Actions</th></tr></thead><tbody>{products.map(p => <tr key={p.id}><td>{p.name}<small>{p.category}</small></td><td>₹{(p.priceMinor / 100).toLocaleString('en-IN')}</td><td><input className="admin-inline-input" type="number" defaultValue={p.stock} onBlur={e => patchProduct(p, { stock: Number(e.target.value) })} /></td><td><button className="admin-text-button" type="button" onClick={() => patchProduct(p, { isActive: !p.isActive })}>{p.isActive ? 'Archive' : 'Publish'}</button></td></tr>)}</tbody></table></Table> : <Empty text="No products have been created yet." />}</>}
    {section === 'orders' && <><Title title="Orders" text="Review orders and update fulfillment status." />{orders.length ? <Table><table className="admin-table"><thead><tr><th>Order</th><th>Total</th><th>Status</th></tr></thead><tbody>{orders.map(o => <tr key={o.id}><td>{o.orderNumber}</td><td>₹{(o.totalMinor / 100).toLocaleString('en-IN')}</td><td><select defaultValue={o.status} onChange={e => patchStatus('/api/admin/orders', { orderId: o.id, status: e.target.value }, 'Order updated.')}><option>PENDING</option><option>CONFIRMED</option><option>PROCESSING</option><option>SHIPPED</option><option>DELIVERED</option><option>CANCELLED</option><option>REFUNDED</option></select></td></tr>)}</tbody></table></Table> : <Empty text="No orders have been placed yet." />}</>}
    {section === 'payments' && <><Title title="Payments" text="Monitor payments and record refunds." />{payments.length ? <Table><table className="admin-table"><thead><tr><th>Order</th><th>Provider</th><th>Amount</th><th>Status</th><th /></tr></thead><tbody>{payments.map((p: any) => <tr key={p.id}><td>{p.order.orderNumber}</td><td>{p.provider}</td><td>₹{(p.amountMinor / 100).toLocaleString('en-IN')}</td><td>{p.status}</td><td>{p.status !== 'REFUNDED' && <button className="admin-text-button danger" type="button" onClick={() => patchStatus('/api/admin/payments', { orderId: p.orderId, action: 'refund' }, 'Refund recorded.')}>Refund</button>}</td></tr>)}</tbody></table></Table> : <Empty text="No payment records yet." />}</>}
    {section === 'returns' && <><Title title="Returns & refunds" text="Review customer return requests and update their resolution." />{returns.length ? <Table><table className="admin-table"><thead><tr><th>Order</th><th>Customer</th><th>Reason</th><th>Status</th></tr></thead><tbody>{returns.map((r: any) => <tr key={r.id}><td>{r.order.orderNumber}</td><td>{r.user.email ?? '—'}</td><td>{r.reason ?? '—'}</td><td><select value={r.status} onChange={e => patchStatus('/api/admin/returns', { returnId: r.id, status: e.target.value }, 'Return updated.')}><option>REQUESTED</option><option>APPROVED</option><option>REJECTED</option><option>REFUNDED</option></select></td></tr>)}</tbody></table></Table> : <Empty text="No return requests yet." />}</>}
    {section === 'customers' && <><Title title="Customers" text="Review customer accounts and order history." />{customers.length ? <Table><table className="admin-table"><thead><tr><th>Name</th><th>Email</th><th>Role</th><th>Orders</th></tr></thead><tbody>{customers.map((c: any) => <tr key={c.id}><td>{c.name ?? '—'}</td><td>{c.email ?? '—'}</td><td>{c.role}</td><td>{c._count.orders}</td></tr>)}</tbody></table></Table> : <Empty text="No customer records yet." />}</>}
    {section === 'messages' && <><Title title="Customer messages" text="Send support and order update emails." /><form className="admin-form" onSubmit={e => submit(e, '/api/admin/messages', 'POST', 'Message sent successfully.')}><label>Recipient email<input name="recipientEmail" type="email" required /></label><label>Subject<input name="subject" required /></label><label className="full">Message<textarea name="body" rows={6} required /></label><button className="primary-button" type="submit">Send message</button></form></>}
    {section === 'analytics' && <><Title title="Analytics" text="Store performance from live database records." /><div className="admin-stat-grid"><Stat label="Revenue" value={`₹${((analytics.revenueMinor ?? 0) / 100).toLocaleString('en-IN')}`} /><Stat label="Orders" value={analytics.orders ?? 0} /><Stat label="Customers" value={analytics.customers ?? 0} /><Stat label="Products" value={analytics.products ?? 0} /></div></>}
    {section === 'settings' && <><Title title="Store settings" text="Configure branding, currency, locale, and announcements." /><form className="admin-form" onSubmit={e => submit(e, '/api/admin/settings', 'PUT', 'Settings saved successfully.')}><label>Store name<input name="storeName" defaultValue={data.settings?.settings?.find((s: any) => s.key === 'storeName')?.value ?? 'Gadgify'} /></label><label>Support email<input name="supportEmail" type="email" /></label><label>Currency<select name="currency" defaultValue="INR"><option>INR</option><option>USD</option><option>EUR</option></select></label><label>Default locale<select name="locale" defaultValue="en-IN"><option>en-IN</option><option>hi-IN</option><option>mr-IN</option></select></label><label className="full">Store announcement<textarea name="announcement" rows={4} /></label><button className="primary-button" type="submit">Save settings</button></form></>}
    {notice && <p className="admin-feedback" role="status">{notice}</p>}
  </div></div></section>
}
function Stat({ label, value }: { label: string; value: string | number }) { return <div><span>{label}</span><strong>{value}</strong></div> }
function Title({ title, text }: { title: string; text: string }) { return <div className="admin-section-title"><div><p className="eyebrow">ADMIN</p><h2>{title}</h2><p>{text}</p></div></div> }
function Panel({ text }: { text: string }) { return <div className="admin-panel"><p>{text}</p></div> }
function Table({ children }: { children: ReactNode }) { return <div className="admin-table-wrap">{children}</div> }
function Empty({ text }: { text: string }) { return <div className="admin-empty"><p>{text}</p></div> }
