import { useEffect, useState, type MouseEvent } from 'react'
import type { StorefrontApiResponse } from '../api/storefront'
type Props = { storefront: StorefrontApiResponse; onNavigate: (path: string) => (event: MouseEvent<HTMLAnchorElement>) => void }
type CartItem = { id: string; quantity: number; product: { id: string; name: string; category: string; priceMinor: number; colors?: { name: string }[] } }
export function CartPage({ storefront, onNavigate }: Props) {
  const { cart } = storefront.content; const [items, setItems] = useState<CartItem[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState('')
  const currency = new Intl.NumberFormat(storefront.localization.locale, { style: 'currency', currency: storefront.localization.currency, maximumFractionDigits: 0 })
  const load = () => { setLoading(true); fetch('/api/cart').then(async response => { if (!response.ok) throw new Error('cart'); const body = await response.json() as { cart?: { items?: CartItem[] } }; setItems(body.cart?.items ?? []); setError('') }).catch(() => setError('Unable to load your cart.')).finally(() => setLoading(false)) }
  useEffect(() => { load() }, [])
  const change = async (item: CartItem, quantity: number) => { if (quantity < 1) await fetch('/api/cart', { method: 'DELETE', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ productId: item.product.id }) }); else await fetch('/api/cart', { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ productId: item.product.id, quantity }) }); load() }
  const total = items.reduce((sum, item) => sum + (item.product.priceMinor / 100) * item.quantity, 0)
  return <section className="page-section cart-page" aria-labelledby="cart-title"><div className="cart-heading"><div><p className="eyebrow">{storefront.content.ui.cartLabel}</p><h1 id="cart-title">{cart.title}</h1><p className="hero-text">Review your selected pieces before checkout.</p></div><span className="cart-count">{items.reduce((sum, item) => sum + item.quantity, 0)} items</span></div>{loading ? <p className="state-message">Loading your cart…</p> : error ? <div className="state-panel"><p>{error}</p><button className="primary-button" type="button" onClick={load}>Try again</button></div> : !items.length ? <div className="wishlist-empty"><p>{cart.emptyDescription}</p><a className="primary-button" href="/products" onClick={onNavigate('/products')}>{cart.continueShoppingLabel}</a></div> : <><div className="cart-list">{items.map(item => <article className="cart-item" key={item.id}><div className="cart-item-art product-art tone-sage"><div className="product-shape" /></div><div className="cart-item-copy"><p>{item.product.category}</p><h3>{item.product.name}</h3><p className="cart-item-detail">Ready to ship · Free returns</p></div><div className="cart-item-controls"><strong>{currency.format((item.product.priceMinor / 100) * item.quantity)}</strong><div className="quantity-control" aria-label={`Quantity for ${item.product.name}`}><button type="button" onClick={() => change(item, item.quantity - 1)} aria-label="Decrease quantity">−</button><span aria-live="polite">{item.quantity}</span><button type="button" onClick={() => change(item, item.quantity + 1)} aria-label="Increase quantity">+</button></div></div></article>)}</div><div className="cart-summary"><span>Estimated total</span><strong>{currency.format(total)}</strong></div><div className="cart-actions"><a className="secondary-button" href="/products" onClick={onNavigate('/products')}>Continue shopping</a><a className="primary-button" href="/checkout" onClick={onNavigate('/checkout')}>Proceed to checkout →</a></div></>}</section>
}
