import { useState, type FormEvent, type MouseEvent } from 'react'
import type { StorefrontApiResponse } from '../api/storefront'

type Props={storefront:StorefrontApiResponse;onNavigate:(path:string)=>(event:MouseEvent<HTMLAnchorElement>)=>void}

export function PaymentPage({storefront,onNavigate}:Props){
  const items=storefront.products.slice(0,2)
  const currency=new Intl.NumberFormat(storefront.localization.locale,{style:'currency',currency:storefront.localization.currency,maximumFractionDigits:0})
  const total=items.reduce((sum,item)=>sum+item.price,0)
  const [submitted,setSubmitted]=useState(false)
  const submit=(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();setSubmitted(true)}
  return <section className="page-section payment-page" aria-labelledby="payment-title"><div className="payment-layout"><div><p className="eyebrow">SECURE CHECKOUT</p><h1 id="payment-title">Complete your order</h1><p className="hero-text">Pay securely online with Razorpay.</p><form className="payment-form" onSubmit={submit}><fieldset><legend>Payment method</legend><div className="payment-option selected"><span className="payment-option-name"><strong>Razorpay</strong><small>Cards, UPI, net banking &amp; wallets</small></span><span className="razorpay-mark">R</span></div></fieldset><div className="payment-info"><p>Razorpay will collect your online payment. Name and email can be passed as Razorpay prefill values; your delivery address is collected separately for fulfillment.</p><p className="payment-note">This demo does not open Razorpay yet. Production requires a server-created order and secret-key signature verification.</p></div><div className="payment-fields"><label>Full name<input required placeholder="Your name" /></label><label>Email address<input required type="email" placeholder="you@example.com" /></label><label>Delivery address<textarea required rows={3} placeholder="Street, city, postal code" /></label></div><button className="primary-button payment-submit" type="submit">Continue to Razorpay <span aria-hidden="true">→</span></button>{submitted&&<p className="payment-success" role="status">Demo order captured. Connect the backend payment endpoint to complete this flow.</p>}</form></div><aside className="order-summary"><p className="eyebrow">YOUR ORDER</p><h2>Order summary</h2>{items.map(item=><div className="summary-line" key={item.id}><span>{item.name}</span><strong>{currency.format(item.price)}</strong></div>)}<div className="summary-total"><span>Total</span><strong>{currency.format(total)}</strong></div><div className="summary-protection">🔒 Secure checkout<br/>Free returns · Support included</div><a href="/bag" onClick={onNavigate('/bag')}>← Return to bag</a></aside></div></section>
}
