import { useEffect, useRef, useState } from 'react'
import { getProducts, type ProductSort, type StorefrontApiResponse, type StorefrontProduct } from '../api/storefront'
import { FilterSidebar } from '../components/FilterSidebar'
import { PromoCarousel } from '../components/PromoCarousel'
import { VirtualizedProductGrid } from '../components/VirtualizedProductGrid'

type Props = { storefront: StorefrontApiResponse; onAdd: () => void; onOpenProduct: (id: string) => void }
export function ShopPage({ storefront, onAdd, onOpenProduct }: Props) {
  const { collection } = storefront.content; const initialSearch = new URLSearchParams(window.location.search).get('search') ?? ''; const [search,setSearch]=useState(initialSearch); const hasSearch = search.trim().length > 0; const [category,setCategory]=useState(''); const [sort,setSort]=useState<ProductSort>('newest'); const [selectedColors,setSelectedColors]=useState<readonly string[]>([]); const [minRating,setMinRating]=useState(0); const [catalog,setCatalog]=useState<readonly StorefrontProduct[]>([]); const [nextCursor,setNextCursor]=useState<string|null>(null); const [loading,setLoading]=useState(true); const sentinel=useRef<HTMLDivElement>(null); const currency=new Intl.NumberFormat(storefront.localization.locale,{style:'currency',currency:storefront.localization.currency,maximumFractionDigits:0})
  useEffect(()=>{let cancelled=false;getProducts({search,category,sort,colors:selectedColors,minRating}).then(page=>{if(cancelled)return;setCatalog(page.products);setNextCursor(page.nextCursor);setLoading(false)});return()=>{cancelled=true}},[category,minRating,search,selectedColors,sort])
  useEffect(()=>{if(!sentinel.current||!nextCursor)return;const observer=new IntersectionObserver(()=>setNextCursor(null),{rootMargin:'300px'});observer.observe(sentinel.current);return()=>observer.disconnect()},[nextCursor])
  const updateSearch=(value:string)=>{setLoading(true);setSearch(value)}; const updateCategory=(value:string)=>{setLoading(true);setCategory(value)}; const toggleColor=(color:string)=>{setLoading(true);setSelectedColors(current=>current.includes(color)?current.filter(item=>item!==color):[...current,color])}; const clear=()=>{setLoading(true);setSearch('');setCategory('');setSort('newest');setSelectedColors([]);setMinRating(0)}
  return <section className="collection-section page-section" aria-labelledby="collection-title">{!hasSearch && <PromoCarousel promos={storefront.content.promotions} previousLabel={collection.carouselPreviousLabel} nextLabel={collection.carouselNextLabel}/>}<div className="section-heading"><div><p className="eyebrow">{collection.eyebrow}</p><h1 id="collection-title">{hasSearch ? `Search results for “${search}”` : collection.title}</h1></div><p className="section-note">{collection.description}</p></div><div className="catalog-layout"><FilterSidebar search={search} category={category} sort={sort} categories={storefront.facets.categories} searchPlaceholder={collection.searchPlaceholder} allCategoriesLabel={collection.allCategoriesLabel} sortLabel={collection.sortLabel} newestSortLabel={collection.newestSortLabel} priceLowSortLabel={collection.priceLowSortLabel} priceHighSortLabel={collection.priceHighSortLabel} clearLabel={collection.clearFiltersLabel} collapseLabel={collection.collapseFiltersLabel} expandLabel={collection.expandFiltersLabel} selectedColors={selectedColors} minRating={minRating} colorOptions={storefront.facets.colors} ratingLabel={collection.ratingLabel} colorsLabel={collection.colorsFilterLabel} benefits={storefront.content.filterBenefits} onSearch={updateSearch} onCategory={updateCategory} onSort={value=>{setLoading(true);setSort(value)}} onRating={value=>{setLoading(true);setMinRating(current=>current===value?0:value)}} onColorToggle={toggleColor} onClear={clear}/><div className="catalog-results"><VirtualizedProductGrid products={catalog} currency={currency} addToCartLabel={collection.addToCartLabel} ratingLabel={collection.ratingLabel} reviewsLabel={collection.reviewsLabel} onAdd={onAdd} onOpenProduct={onOpenProduct}/>{!loading&&catalog.length===0&&<p className="empty-state">{collection.noResultsLabel}</p>}</div></div>{!loading&&catalog.length>0&&!nextCursor&&<div className="catalog-end" role="status"><span>{collection.catalogEndLabel}</span><button type="button" onClick={()=>window.scrollTo({top:0,behavior:'smooth'})}>{collection.catalogEndActionLabel} ↑</button></div>}<div className="catalog-sentinel" ref={sentinel} aria-live="polite">{loading||nextCursor?collection.loadingMoreLabel:''}</div></section>
}
